version: 1.0.0

phases:
  install:
    commands:
      - npm install
      - npm install -g yarn
      - yarn install
      - npm install -g serverless
  build:
    commands:
      - serverless deploy --stage prod
