Resources:
  ServiceALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: alb-cloud-pci-bff-${self:provider.environmentShort}
      Subnets:
        - ${ssm:/CP/CLOUD-PCI/SUBNET1}
        - ${ssm:/CP/CLOUD-PCI/SUBNET2}
        - ${ssm:/CP/CLOUD-PCI/SUBNET3}
      Scheme: internal
      SecurityGroups:
        - ${ssm:/CP/CLOUD-PCI/SECUTIRYGROUPELB}
  LoadBalancerListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ServiceALB
      Certificates:
        - CertificateArn: ${ssm:/CP/CLOUD-PCI/SSLCERTIFICATE}
      Port: '443'
      Protocol: HTTPS
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: 200
            ContentType: "text/plain"
            MessageBody: "Success"
