Resources:
  ServiceALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: alb-cloud-pci-bff-${self:provider.environmentShort}
      Subnets:
        - ${ssm:/CP/CLOUD-PCI/SUBNET1}
        - ${ssm:/CP/CLOUD-PCI/SUBNET2}
        - ${ssm:/CP/CLOUD-PCI/SUBNET3}
      Scheme: internal
      SecurityGroups:
        - ${ssm:/CP/CLOUD-PCI/SECUTIRYGROUPELB}
  LoadBalancerListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ServiceALB
      Port: '80'
      Protocol: HTTP
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: 200
            ContentType: "text/plain"
            MessageBody: "Success"
  LoadBalancerListenerHTTPHealthCheckRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: redirect
          RedirectConfig:
            Host: "#{host}"
            Path: "/healthcheck"
            Port: "#{port}"
            Protocol: "#{protocol}"
            StatusCode: HTTP_301
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - "/healthcheck"
      ListenerArn: !Ref LoadBalancerListenerHTTP
      Priority: 2
  LoadBalancerListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ServiceALB
      Certificates:
        - CertificateArn: ${ssm:/CP/CLOUD-PCI/SSLCERTIFICATE}
      Port: '443'
      Protocol: HTTPS
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: 200
            ContentType: "text/plain"
            MessageBody: "Success"
  LoadBalancerListenerHTTPSHealthCheckRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref CloudDashpciDashbffAlbTargetGroupLoadBalancerListenerHTTPS
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - "/v1/pci-bff/support/healthcheck"
      ListenerArn: !Ref LoadBalancerListenerHTTPS
      Priority: 1
