service: pci-grabber-bff

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true   # Node modules configuration for packaging
    packager: 'npm'   # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
  environments:
    dev: DEV
    exe: EXE
    prod: PROD
    local: LOCAL

provider:
  name: aws
  runtime: nodejs12.x
  endpointType: PRIVATE
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment: ${file(env.yml)}

iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:ListBucket"
    Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
  - Effect: "Allow"
    Action:
      - "s3:PutObject"
    Resource:
      Fn::Join:
        - ""
        - - "arn:aws:s3:::"
          - "Ref" : "ServerlessDeploymentBucket"
          - "/*"

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  pci-grabber-bff:
    handler: src/index.serverlessApp
    events: ${file(./serverless-routes.js)}
    environment:
      ENVIRONMENT_NAME: ${opt:stage, 'dev'}
      PORT: ${opt:port, 4000}
    memorySize: 1024
    timeout: 60

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
