service: pci-grabber-bff

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true   # Node modules configuration for packaging
    packager: 'npm'   # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
  environments:
    dev: DEV
    exe: EXE
    prod: PROD
    local: LOCAL
  deploymentBucket:
    local: local
    dev: ${ssm:/CP/PCI-GRABBER/DEV/DEPLOYMENTBUCKET}
    exe: ${ssm:/CP/PCI-GRABBER/EXE/DEPLOYMENTBUCKET}
    prod: ${ssm:/CP/PCI-GRABBER/PROD/DEPLOYMENTBUCKET}

provider:
  name: aws
  runtime: nodejs12.x
  project: pci-grabber-bff
  stage: ${opt:stage, 'dev'}
  environmentShort: ${file(./env.yml):${self:provider.stage}.STAGE}
  region: ${file(./env.yml):${self:provider.stage}.REGION}
  environment: ${file(./env.yml):${self:provider.stage}}
  deploymentBucket: ${self:custom.deploymentBucket.${self:provider.stage}}
  deploymentPrefix: pci-grabber-bff
  stackTags: ${file(AwsTags.yml):${self:provider.stage}}
  vpc:
    securityGroupIds:
      - ${ssm:/CP/PCI-GRABBER/SECUTIRYGROUP1}
      - ${ssm:/CP/PCI-GRABBER/SECUTIRYGROUP2}
      - ${ssm:/CP/PCI-GRABBER/SECUTIRYGROUP3}
    subnetIds:
      - ${ssm:/CP/PCI-GRABBER/SUBNET1}
      - ${ssm:/CP/PCI-GRABBER/SUBNET2}
      - ${ssm:/CP/PCI-GRABBER/SUBNET3}
  role: ${ssm:/CP/PCI-GRABBER/EXECUTIONROLE}
  alb:
    targetGroupPrefix: pci-grabber-${self:provider.environmentShort}

resources:
  - ${file(./serverless.resources.yml)}

functions:
  pci-grabber-bff:
    name: pci-grabber-bff-${self:provider.environmentShort}
    handler: src/app.serverlessApp
    # events: ${file(./serverless-routes.js)}
    environment:
      ENVIRONMENT: ${self:provider.environmentShort}
      PORT: ${opt:port, 4000}
    memorySize: 512
    timeout: 60
    events:
     - alb:
         listenerArn: !Ref LoadBalancerListenerHTTP
         priority: 1
         conditions:
           path: /v1/*
