import {
    CIPZ_API_ERROR_CODES,
    CIPZ_ERROR_CODE_MAP,
    GENERAL_EXCEPTION,
} from './exceptionCodes';

export const CIPZAPIToPZRErrorMap = new Map([
    [CIPZ_API_ERROR_CODES.INVALID_BUSINESS_UNIT_ERROR_CODE, CIPZ_ERROR_CODE_MAP.INVALID_BUSINESS_UNIT_ERROR_CODE],
    [CIPZ_API_ERROR_CODES.INVALID_CURRENT_PRICE_ZONE_ERROR_CODE, CIPZ_ERROR_CODE_MAP.INVALID_CURRENT_PRICE_ZONE_ERROR_CODE],
    [CIPZ_API_ERROR_CODES.INVALID_CUSTOMER_ACCOUNT_CUSTOMER_GROUP_ERROR_CODE,
    CIPZ_ERROR_CODE_MAP.INVALID_CUSTOMER_ACCOUNT_CUSTOMER_GROUP_ERROR_CODE],
    [CIPZ_API_ERROR_CODES.INVALID_CUSTOMER_ACCOUNT_ERROR_CODE, CIPZ_ERROR_CODE_MAP.INVALID_CUSTOMER_ACCOUNT_ERROR_CODE],
    [CIPZ_API_ERROR_CODES.INVALID_EFFECTIVE_FROM_DATE_ERROR_CODE, CIPZ_ERROR_CODE_MAP.INVALID_EFFECTIVE_FROM_DATE_ERROR_CODE],
    [CIPZ_API_ERROR_CODES.INVALID_ITEM_ATTRIBUTE_GROUP_ERROR_CODE, CIPZ_ERROR_CODE_MAP.INVALID_ITEM_ATTRIBUTE_GROUP_ERROR_CODE],
    [CIPZ_API_ERROR_CODES.INVALID_ITEM_ATTRIBUTE_GROUP_ID_ERROR_CODE, CIPZ_ERROR_CODE_MAP.INVALID_ITEM_ATTRIBUTE_GROUP_ID_ERROR_CODE],
    [CIPZ_API_ERROR_CODES.INVALID_LIMIT_ERROR_CODE, CIPZ_ERROR_CODE_MAP.INVALID_LIMIT_ERROR_CODE],
    [CIPZ_API_ERROR_CODES.INVALID_NEW_PRICE_ZONE_ERROR_CODE, CIPZ_ERROR_CODE_MAP.INVALID_NEW_PRICE_ZONE_ERROR_CODE],
    [CIPZ_API_ERROR_CODES.INVALID_OFFSET_ERROR_CODE, CIPZ_ERROR_CODE_MAP.INVALID_OFFSET_ERROR_CODE],
    [CIPZ_API_ERROR_CODES.INVALID_REQUEST_ID_ERROR_CODE, CIPZ_ERROR_CODE_MAP.INVALID_REQUEST_ID_ERROR_CODE],
    [CIPZ_API_ERROR_CODES.INVALID_REQUEST_STATUS_ERROR_CODE, CIPZ_ERROR_CODE_MAP.INVALID_REQUEST_STATUS_ERROR_CODE],
    [CIPZ_API_ERROR_CODES.INVALID_REVIEVER_NOTE_ERROR_CODE, CIPZ_ERROR_CODE_MAP.INVALID_REVIEVER_NOTE_ERROR_CODE],
    [CIPZ_API_ERROR_CODES.INVALID_SUBITTER_NOTE_ERROR_CODE, CIPZ_ERROR_CODE_MAP.INVALID_SUBITTER_NOTE_ERROR_CODE],
    [CIPZ_API_ERROR_CODES.INVALID_SUBMITTER_ERROR_CODE, CIPZ_ERROR_CODE_MAP.INVALID_SUBMITTER_ERROR_CODE],
    [CIPZ_API_ERROR_CODES.ITEM_PRICE_ZONE_DETAILS_UNAVAILABLE_ERROR_CODE, CIPZ_ERROR_CODE_MAP.ITEM_PRICE_ZONE_DETAILS_UNAVAILABLE_ERROR_CODE],
    [CIPZ_API_ERROR_CODES.REQUESTED_UPDATE_STATE_CHANGED_ALREADY_ERROR_CODE, CIPZ_ERROR_CODE_MAP.REQUESTED_UPDATE_STATE_CHANGED_ALREADY_ERROR_CODE],
    [CIPZ_API_ERROR_CODES.REQUEST_ID_NOT_FOUND_ERROR_CODE, CIPZ_ERROR_CODE_MAP.REQUEST_ID_NOT_FOUND_ERROR_CODE],
    [CIPZ_API_ERROR_CODES.UNKNOWN_ERROR_CODE, GENERAL_EXCEPTION],
]);
