/**
 2000 - 2999 -> Downstream API Exceptions
 3000 - 3999 -> Configuration Exceptions
 4000 - 4999 -> Other
*/

export const GENERAL_EXCEPTION = 4000;

export const HTTP_CLIENT_EXCEPTION = 2000;
export const API_CENTRAL_EXCEPTION = 2001;

/* Specific error codes */
export const PCI_PRICE_DATA_FETCH_ERROR_CODE = 2020;
export const PRODUCT_PRICE_DATA_FETCH_ERROR_CODE = 2021;
export const PRODUCT_INFO_DATA_FETCH_ERROR_CODE = 2022;
export const PRICING_DATA_INVALID_PAYLOAD_ERROR_CODE = 2023;
export const USER_UNAUTHORIZED_ERROR_CODE = 2024;
export const CUSTOMER_INFO_DATA_FETCH_ERROR_CODE = 2025;

export const INVALID_REQUEST_BODY_CODE = 2027;
export const EMPTY_REQUEST_BODY_CODE = 2028;
export const BATCH_API_DATA_FETCH_ERROR_CODE = 2029;
export const INTERNAL_SERVER_ERROR_CODE = 4000;

export const UNKNOWN_SEED_API_ERROR = 5005;
export const UNKNOWN_CIPZ_API_ERROR = 6005;

// validation and other CIPZ Error codes
// TODO Remove unused
export const CIPZ_SEED_VALIDATION_AND_GENERAL_ERROR_CODES = {
    SEED_API_ITEM_ATT_GROUP_FETCH_ERROR_CODE: 4028,
    SEED_API_CUSTOMER_ITEM_ATTRIBUTR_GROUP_FETCH_ERROR_CODE: 4040,
    SEED_API_CUSTOMER_GROUP_ITEM_ATTRIBUTR_GROUP_FETCH_ERROR_CODE: 4041,
    CIPZ_API_DATA_FETCH_ERROR_CODE: 4029,
    CIPZ_API_CREATE_PRICE_ZONE_UPDATE_ERROR_CODE: 4030,
    ERROR_IN_FETCHING_SEED_ITEM_ATTRIBUTE_GROUP_DATA_CODE: 4031,
    PRICE_ZONE_REASSIGNMENT_INVALID_SEARCH_PAYLOAD_ERROR_CODE: 4032,
    PRICE_ZONE_REASSIGNMENT_INVALID_UPDATE_PAYLOAD_ERROR_CODE: 4033,
    RESPONSING_CIPZ_PRICE_ZONE_APPROVAL_REQ_ERROR_CODE: 4034,
    CPIZ_API_DATA_INVALID_PAYLOAD_ERROR_CODE: 4035,
    CPIZ_API_DATA_INVALID_QUERY_PARAMS_ERROR_CODE: 4036,
    UPDATING_CIPZ_PRICE_ZONE_SUBMITTED_REQ_ERROR_CODE: 4037,
    SEED_API_SOMETHING_WENT_WRONG: 4038,
    SEED_API_DATA_NOT_FOUND: 4039,
};
