/**
 2000 - 2999 -> Downstream API Exceptions
 3000 - 3999 -> Configuration Exceptions
 4000 - 4999 -> Other
 */

export const GENERAL_EXCEPTION = 4000;

export const HTTP_CLIENT_EXCEPTION = 2000;
export const API_CENTRAL_EXCEPTION = 2001;

/* Specific error codes */
export const PCI_PRICE_DATA_FETCH_ERROR_CODE = 2020;
export const PRODUCT_PRICE_DATA_FETCH_ERROR_CODE = 2021;
export const PRODUCT_INFO_DATA_FETCH_ERROR_CODE = 2022;
export const PRICING_DATA_INVALID_PAYLOAD_ERROR_CODE = 2023;
export const USER_UNAUTHORIZED_ERROR_CODE = 2024;
export const CUSTOMER_INFO_DATA_FETCH_ERROR_CODE = 2025;

export const INVALID_REQUEST_BODY_CODE = 2027;
export const EMPTY_REQUEST_BODY_CODE = 2028;
export const BATCH_API_DATA_FETCH_ERROR_CODE = 2029;
export const SEED_API_ITEM_ATT_GROUP_FETCH_ERROR_CODE = 2030;
export const PRICE_ZONE_REASSIGNMENT_INVALID_SEARCH_PAYLOAD_ERROR_CODE = 2031;

export const INTERNAL_SERVER_ERROR_CODE = 4000;
